/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PovijestRouteImport } from './routes/povijest'
import { Route as PonudaJednostavnaRouteImport } from './routes/ponuda-jednostavna'
import { Route as PonudaDetaljnaRouteImport } from './routes/ponuda-detaljna'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredlozakIdRouteImport } from './routes/predlozak.$id'

const PovijestRoute = PovijestRouteImport.update({
  id: '/povijest',
  path: '/povijest',
  getParentRoute: () => rootRouteImport,
} as any)
const PonudaJednostavnaRoute = PonudaJednostavnaRouteImport.update({
  id: '/ponuda-jednostavna',
  path: '/ponuda-jednostavna',
  getParentRoute: () => rootRouteImport,
} as any)
const PonudaDetaljnaRoute = PonudaDetaljnaRouteImport.update({
  id: '/ponuda-detaljna',
  path: '/ponuda-detaljna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredlozakIdRoute = PredlozakIdRouteImport.update({
  id: '/predlozak/$id',
  path: '/predlozak/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ponuda-detaljna': typeof PonudaDetaljnaRoute
  '/ponuda-jednostavna': typeof PonudaJednostavnaRoute
  '/povijest': typeof PovijestRoute
  '/predlozak/$id': typeof PredlozakIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ponuda-detaljna': typeof PonudaDetaljnaRoute
  '/ponuda-jednostavna': typeof PonudaJednostavnaRoute
  '/povijest': typeof PovijestRoute
  '/predlozak/$id': typeof PredlozakIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ponuda-detaljna': typeof PonudaDetaljnaRoute
  '/ponuda-jednostavna': typeof PonudaJednostavnaRoute
  '/povijest': typeof PovijestRoute
  '/predlozak/$id': typeof PredlozakIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ponuda-detaljna'
    | '/ponuda-jednostavna'
    | '/povijest'
    | '/predlozak/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ponuda-detaljna'
    | '/ponuda-jednostavna'
    | '/povijest'
    | '/predlozak/$id'
  id:
    | '__root__'
    | '/'
    | '/ponuda-detaljna'
    | '/ponuda-jednostavna'
    | '/povijest'
    | '/predlozak/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PonudaDetaljnaRoute: typeof PonudaDetaljnaRoute
  PonudaJednostavnaRoute: typeof PonudaJednostavnaRoute
  PovijestRoute: typeof PovijestRoute
  PredlozakIdRoute: typeof PredlozakIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/povijest': {
      id: '/povijest'
      path: '/povijest'
      fullPath: '/povijest'
      preLoaderRoute: typeof PovijestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponuda-jednostavna': {
      id: '/ponuda-jednostavna'
      path: '/ponuda-jednostavna'
      fullPath: '/ponuda-jednostavna'
      preLoaderRoute: typeof PonudaJednostavnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponuda-detaljna': {
      id: '/ponuda-detaljna'
      path: '/ponuda-detaljna'
      fullPath: '/ponuda-detaljna'
      preLoaderRoute: typeof PonudaDetaljnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predlozak/$id': {
      id: '/predlozak/$id'
      path: '/predlozak/$id'
      fullPath: '/predlozak/$id'
      preLoaderRoute: typeof PredlozakIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PonudaDetaljnaRoute: PonudaDetaljnaRoute,
  PonudaJednostavnaRoute: PonudaJednostavnaRoute,
  PovijestRoute: PovijestRoute,
  PredlozakIdRoute: PredlozakIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
